-- MySQL Script generated by MySQL Workbench
-- Thu Jun 21 16:33:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_exchange
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_exchange
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_exchange` DEFAULT CHARACTER SET utf8 COLLATE=utf8_general_ci;
USE `db_exchange` ;

CREATE TABLE `admin_menu` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `order` int(11) NOT NULL DEFAULT '0',
  `title` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `uri` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_operation_log"
#

CREATE TABLE `admin_operation_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `method` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ip` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  `input` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `admin_operation_log_user_id_index` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_permissions"
#

CREATE TABLE `admin_permissions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `http_method` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `http_path` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `admin_permissions_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_role_menu"
#

CREATE TABLE `admin_role_menu` (
  `role_id` int(11) NOT NULL,
  `menu_id` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  KEY `admin_role_menu_role_id_menu_id_index` (`role_id`,`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_role_permissions"
#

CREATE TABLE `admin_role_permissions` (
  `role_id` int(11) NOT NULL,
  `permission_id` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  KEY `admin_role_permissions_role_id_permission_id_index` (`role_id`,`permission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_role_users"
#

CREATE TABLE `admin_role_users` (
  `role_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  KEY `admin_role_users_role_id_user_id_index` (`role_id`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_roles"
#

CREATE TABLE `admin_roles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `admin_roles_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_user_permissions"
#

CREATE TABLE `admin_user_permissions` (
  `user_id` int(11) NOT NULL,
  `permission_id` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  KEY `admin_user_permissions_user_id_permission_id_index` (`user_id`,`permission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "admin_users"
#

CREATE TABLE `admin_users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `admin_users_username_unique` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "migrations"
#

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "password_resets"
#

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#
# Structure for table "t_admin"
#

CREATE TABLE `t_admin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_name` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '账号',
  `position` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '职位名称',
  `password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '密码',
  `salt` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '盐值',
  `status` char(1) COLLATE utf8mb4_bin DEFAULT '0' COMMENT '状态(0:正常 1:禁用)',
  `creator` char(36) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人ID',
  `remark` text COLLATE utf8mb4_bin COMMENT '备注',
  `createTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `lastTime` datetime DEFAULT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_name_UNIQUE` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='管理员/运营人员的基本信息';

#
# Structure for table "t_admin_log"
#

CREATE TABLE `t_admin_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) unsigned NOT NULL,
  `type` varchar(10) COLLATE utf8mb4_bin NOT NULL COMMENT '用户操作类型',
  `add_time` int(11) unsigned NOT NULL COMMENT '操作的时间',
  `operation_ip` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户操作的ip',
  `comment` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户操作时提供的参数',
  PRIMARY KEY (`id`),
  KEY `fk_user_log_admin_id_idx` (`admin_id`),
  CONSTRAINT `fk_user_log_admin_id` FOREIGN KEY (`admin_id`) REFERENCES `t_admin` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='管理员日志，管理员涉及到修改的接口都要记录日志';

#
# Structure for table "t_admin_resources"
#

CREATE TABLE `t_admin_resources` (
  `res_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '资源ID',
  `name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '资源名称',
  `res_level` tinyint(2) NOT NULL COMMENT '资源类别(1:一级菜单,2:二级菜单,3:三级菜单)',
  `url` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '资源URL',
  `pre_id` int(11) DEFAULT NULL COMMENT '父菜单ID',
  `sort_index` int(6) DEFAULT NULL COMMENT '排序(菜单顺序)',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 ',
  `last_up_time` datetime DEFAULT NULL COMMENT '最后更新时间 ',
  PRIMARY KEY (`res_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='资源表';

#
# Structure for table "t_admin_role"
#

CREATE TABLE `t_admin_role` (
  `role_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `name` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '角色名称',
  `create_user_id` char(36) COLLATE utf8mb4_bin NOT NULL COMMENT '创建用户编号',
  `des` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 ',
  `last_up_time` datetime DEFAULT NULL COMMENT '最后更新时间 ',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '角色状态(0:正常 1:禁用)',
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `inx_osr_role_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='角色表';

#
# Structure for table "t_admin_role_res"
#

CREATE TABLE `t_admin_role_res` (
  `role_id` int(11) unsigned NOT NULL COMMENT '角色ID',
  `res_id` int(11) NOT NULL COMMENT '资源ID',
  PRIMARY KEY (`role_id`,`res_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='角色资源表';

#
# Structure for table "t_admin_token"
#

CREATE TABLE `t_admin_token` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `token` varchar(64) NOT NULL COMMENT 'token',
  `expire_time` datetime NOT NULL COMMENT '过期时间',
  `last_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_userId` (`user_id`),
  KEY `idx_token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='管理用户token表';

#
# Structure for table "t_admin_user_role"
#

CREATE TABLE `t_admin_user_role` (
  `user_id` int(11) unsigned NOT NULL COMMENT '用户id',
  `role_id` int(11) NOT NULL COMMENT '角色ID',
  PRIMARY KEY (`user_id`,`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='用户角色表';

#
# Structure for table "t_advertise"
#

CREATE TABLE `t_advertise` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '广告名称',
  `position` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '广告位置',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `status` int(11) DEFAULT NULL COMMENT '0:上线  1:下线',
  `url` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '广告图片',
  `link` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '广告链接',
  `remark` text COLLATE utf8mb4_bin COMMENT '备注',
  `createTime` datetime NOT NULL COMMENT '创建时间',
  `lastTime` datetime DEFAULT NULL COMMENT '更新时间',
  `type` tinyint(4) DEFAULT NULL COMMENT '类型：0:链接  1:图文',
  `content` text COLLATE utf8mb4_bin COMMENT '图文富文本',
  `locale` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '语言版本， 格式: 语言_国家， 比如zh_CN,zh_TW, en_US',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='广告信息表';

#
# Structure for table "t_app_version"
#

CREATE TABLE `t_app_version` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` int(11) DEFAULT NULL COMMENT '序号',
  `version_name` varchar(20) DEFAULT NULL COMMENT '版本',
  `platform` varchar(25) DEFAULT NULL COMMENT '平台',
  `url` varchar(255) DEFAULT NULL COMMENT '地址',
  `content` varchar(255) DEFAULT NULL COMMENT '内容',
  `force` int(11) DEFAULT NULL COMMENT '(0-非强制，1-强制)',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `last_time` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Structure for table "t_article"
#

CREATE TABLE `t_article` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '文章标题',
  `type` tinyint(4) NOT NULL COMMENT '文章类型 1:公告 2：行业资讯',
  `locale` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '语言版本， 格式: 语言_国家， 比如zh_CN,zh_TW, en_US',
  `content` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '详细内容，富文本',
  `status` tinyint(4) NOT NULL COMMENT '文章状态， 1: 显示 2：不显示',
  `creator` int(11) unsigned NOT NULL COMMENT '创建人id',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '最近一次修改的时间',
  `display_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '显示时间，如果不设置就是最后更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='文章记录表';

#
# Structure for table "t_cash_monitoring_config"
#

CREATE TABLE `t_cash_monitoring_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(20) NOT NULL COMMENT '币种名字',
  `roll_in_number` varchar(20) DEFAULT NULL COMMENT '转入的数量',
  `roll_out_number` varchar(20) DEFAULT NULL COMMENT '转出的数量',
  `last_refresh_time` int(20) DEFAULT '0' COMMENT '上次刷新的时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_coin"
#

CREATE TABLE `t_coin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(8) NOT NULL DEFAULT '' COMMENT '币种名称，全局唯一',
  `symbol` varchar(8) NOT NULL COMMENT '币种符号，有可能会出现重复，在以太坊上面有很多重名符号的代币',
  `category` varchar(8) NOT NULL COMMENT '币种种类，目前主要有btc和eth，token，real，用于区分是属于哪一种公链的币或山寨币，同步的时候需要用不同的策略',
  `display_name` varchar(32) NOT NULL COMMENT '默认显示名称，在没有找到对应语言的显示的时候，显示这个名字',
  `display_name_all` varchar(255) DEFAULT NULL COMMENT '多语言的显示名，每行一种语言，以语言简称开始，比如zh:以太币，表示中文的以太币名称，这个只用于界面显示，不用于查询搜索',
  `image` varchar(128) DEFAULT NULL COMMENT '显示图片',
  `icon` varchar(128) NOT NULL COMMENT '符号图片，小图',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `status` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '状态，0：正常，1：禁止使用',
  `server_address` varchar(100) NOT NULL COMMENT '币种的服务器地址，用于转入转出使用',
  `server_port` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '币种的服务器端口，用于转入转出使用',
  `server_user` varchar(45) DEFAULT NULL COMMENT '币种服务器连接所用的用户名',
  `server_password` varchar(45) DEFAULT NULL COMMENT '币种服务器连接所用的密码',
  `send_fee` float(8,4) unsigned NOT NULL DEFAULT '0.0000' COMMENT '对外发送币所需要收的手续费，暂时废弃',
  `received_fee` float(8,4) unsigned NOT NULL DEFAULT '0.0000' COMMENT '从外接收币所需要收的手续费,小数',
  `contract_address` varchar(64) DEFAULT NULL COMMENT '以太坊合约地址，只有以太坊代币才有用',
  `coin_self_parameter` varchar(500) DEFAULT NULL COMMENT '币种本身的一些参数，非公有的，用于扩展，由币种类型确定，一般采用json格式',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次修改时间',
  `coin_base` varchar(128) DEFAULT NULL COMMENT '主账户地址',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币种基本信息';

#
# Structure for table "t_coin_config"
#

CREATE TABLE `t_coin_config` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(32) NOT NULL COMMENT '币名',
  `transfer_fee_rate` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '转账手续费',
  `transfer_fee_static` decimal(10,4) DEFAULT '0.0000' COMMENT '转账收取固定值',
  `transfer_fee_select` int(11) DEFAULT '0' COMMENT '手续费方式:0百分1固定',
  `transfer_min_amount` decimal(32,8) DEFAULT '0.00000000' COMMENT '转账最小值',
  `transfer_max_amount` decimal(32,8) DEFAULT '0.00000000' COMMENT '转账最大值',
  `node_confirm_count` int(11) DEFAULT '3' COMMENT '转账节点确认数',
  `maximum_amount_day` decimal(32,8) DEFAULT '0.00000000' COMMENT '当天最大提币数量',
  `maximum_number_day` int(11) DEFAULT '1' COMMENT '当天最大提币次数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_coinname` (`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_coin_difference"
#

CREATE TABLE `t_coin_difference` (
  `coin_name` varchar(20) NOT NULL,
  `roll_in_total` decimal(18,8) DEFAULT NULL COMMENT '历史该币种转入总数',
  `tody_add_roll_in_total` decimal(18,8) DEFAULT NULL COMMENT '今日新增的数量',
  `user_balance_total` decimal(18,8) DEFAULT NULL COMMENT '用户该币种总余额',
  `point_total` decimal(18,8) DEFAULT NULL COMMENT '历史积分总数',
  `today_add_point_total` decimal(18,8) DEFAULT NULL COMMENT '今日新增的币的数量',
  `refresh_time` datetime DEFAULT NULL COMMENT '服务器刷新监控时间点',
  PRIMARY KEY (`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_coin_difference_config"
#

CREATE TABLE `t_coin_difference_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `coin_name` varchar(20) NOT NULL COMMENT '币种',
  `more_difference` varchar(20) NOT NULL COMMENT '转入比平台内多出的数量',
  `less_difference` varchar(20) NOT NULL COMMENT '转入与当前平台少的差额',
  `refresh_time` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_coin_group_config"
#

CREATE TABLE `t_coin_group_config` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL COMMENT '分组对应的Id,对应用户分组表',
  `coin_name` varchar(20) NOT NULL DEFAULT '' COMMENT '币种名字',
  `con_value` varchar(20) DEFAULT '0' COMMENT '对应的配置值（如手续费、）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '0:表示未禁用 1：表示禁用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='参数设置-手续费设置,例如：USDT单边收取卖家手续费；平台单边收取的手续费';

#
# Structure for table "t_coin_stat"
#

CREATE TABLE `t_coin_stat` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `coin_name` varchar(20) DEFAULT NULL COMMENT '币种名称',
  `total_fee` decimal(18,8) DEFAULT NULL COMMENT '该币种历史总手续费统计',
  `last_refresh_time` int(20) DEFAULT '0' COMMENT '最近刷新时间',
  `total_cureency` decimal(18,8) DEFAULT NULL COMMENT '币种总数量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='统计币种历史总手续费';

#
# Structure for table "t_config"
#

CREATE TABLE `t_config` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `conf_name` varchar(50) NOT NULL DEFAULT '' COMMENT '名称，必须唯一，用英文不要用空格',
  `conf_value` varchar(1000) DEFAULT NULL COMMENT '属性的值',
  `comment` varchar(40) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (`id`),
  UNIQUE KEY `key_name_UNIQUE` (`conf_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全局配置表，保存一些基本配置信息或参数，也用于做某些后台任务的锁定，任务启动时锁定某行，避免一个任务在多个服务器上同时执行';

#
# Structure for table "t_cron_config"
#

CREATE TABLE `t_cron_config` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cron_name` varchar(128) DEFAULT NULL COMMENT 'cron名称',
  `cron_type` int(11) DEFAULT NULL COMMENT '定时器类型：1cron,2simple',
  `cron_expression` varchar(32) DEFAULT NULL COMMENT 'cron表达式',
  `cron_no` varchar(32) DEFAULT NULL COMMENT '编号',
  `status` int(11) DEFAULT '0' COMMENT '状态:0停止，1启动',
  `cron_className` varchar(128) DEFAULT NULL COMMENT '类全名',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_delay_release"
#

CREATE TABLE `t_delay_release` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `release_time` datetime NOT NULL COMMENT '释放的时间',
  `coin_name` varchar(12) NOT NULL DEFAULT '' COMMENT '币种',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `amount` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '释放的金额',
  `had_release` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '释放已经释放',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '最后一次释放时间',
  PRIMARY KEY (`id`),
  KEY `release_time` (`release_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='延迟释放奖励，到了时间释放固定冻结金';

#
# Structure for table "t_delay_shareout"
#

CREATE TABLE `t_delay_shareout` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '币种名称',
  `change_amount` decimal(24,8) NOT NULL DEFAULT '0.00000000' COMMENT '奖励金额',
  `user_base_coin` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户资金（BON)',
  `comment` varchar(100) DEFAULT NULL COMMENT '备注信息',
  `add_time` datetime DEFAULT NULL COMMENT '添加时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于提高性能，保存的中间表格';

#
# Structure for table "t_dispatch_config"
#

CREATE TABLE `t_dispatch_config` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cron_id` int(11) DEFAULT NULL COMMENT '定时任务ID',
  `cron_name` varchar(128) DEFAULT NULL COMMENT '定时任务名称',
  `lock_name` varchar(32) DEFAULT NULL COMMENT '锁仓名称',
  `lock_rate` decimal(10,4) DEFAULT '0.0000' COMMENT '锁仓比例',
  `free_rate` decimal(10,4) DEFAULT '0.0000' COMMENT '释放比例',
  `status` int(11) DEFAULT '0' COMMENT '1开启，0关闭',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_dispatch_job"
#

CREATE TABLE `t_dispatch_job` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `mobile` varchar(128) DEFAULT NULL,
  `cron_id` int(11) DEFAULT NULL COMMENT '定时器ID(属于那批定时任务)',
  `cron_name` varchar(128) DEFAULT NULL COMMENT '定时任务名称',
  `dispatch_no` varchar(32) DEFAULT NULL COMMENT '拨币编号',
  `coin_name` varchar(10) DEFAULT NULL COMMENT '币种',
  `comment` varchar(128) DEFAULT NULL COMMENT '任务说明',
  `amount` decimal(32,8) DEFAULT NULL COMMENT '剩余数量',
  `amount_all` decimal(32,8) DEFAULT NULL COMMENT '总共拨币多少',
  `lock_rate` decimal(32,8) DEFAULT NULL COMMENT '锁仓比例',
  `free_rate` decimal(32,8) DEFAULT NULL COMMENT '释放比例',
  `status` int(11) DEFAULT NULL COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_createtime` (`create_time`),
  KEY `idx_cronid` (`cron_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_dispatch_log"
#

CREATE TABLE `t_dispatch_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL COMMENT '用户ID',
  `mobile` varchar(128) DEFAULT NULL COMMENT '手机号',
  `coin_name` varchar(10) DEFAULT NULL COMMENT '币种',
  `amount` decimal(32,8) DEFAULT NULL COMMENT '数量',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_etc_address"
#

CREATE TABLE `t_etc_address` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL COMMENT '用户ID',
  `address` varchar(64) DEFAULT NULL COMMENT '地址',
  `password` varchar(32) DEFAULT NULL COMMENT '地址秘钥',
  `filename` varchar(128) DEFAULT NULL COMMENT '文件名字',
  `credentials` text COMMENT '秘钥凭证',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_eth_address"
#

CREATE TABLE `t_eth_address` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL COMMENT '用户ID',
  `address` varchar(64) DEFAULT NULL COMMENT '地址',
  `password` varchar(32) DEFAULT NULL COMMENT '地址秘钥',
  `filename` varchar(128) DEFAULT NULL COMMENT '文件名字',
  `credentials` text COMMENT '秘钥凭证',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_exchange_rate"
#

CREATE TABLE `t_exchange_rate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '需要买入或卖出的币种',
  `settlement_currency` varchar(8) NOT NULL DEFAULT '' COMMENT '用于结算的货币',
  `price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '价格，表示1个coin需要多少个结算货币进行兑换',
  `comment` varchar(50) DEFAULT NULL COMMENT '用于说明一些信息，比如来源于那个站点的',
  `add_time` datetime NOT NULL COMMENT '记录增加的时间',
  `update_time` datetime NOT NULL COMMENT '最后一次修改时间',
  `price_hour_ago` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '一小时前价格',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_ex_coin_currency` (`settlement_currency`,`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='汇率表，收集2种货币兑换的价格';

#
# Structure for table "t_google_auth"
#

CREATE TABLE `t_google_auth` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mobile` varchar(128) NOT NULL COMMENT '手机号，email',
  `type` varchar(6) NOT NULL COMMENT '类型',
  `code` varchar(16) DEFAULT NULL COMMENT 'google验证码',
  `status` int(11) DEFAULT '0' COMMENT '验证状态',
  `lastTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '超时时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mobile_type` (`mobile`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_google_secret"
#

CREATE TABLE `t_google_secret` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL COMMENT '用户ID',
  `secret` varchar(128) DEFAULT NULL COMMENT 'Google秘钥',
  `status` int(11) DEFAULT '0' COMMENT '0未绑定，1绑定OK',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_userid` (`user_id`),
  KEY `idx_secret` (`secret`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_market"
#

CREATE TABLE `t_market` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(10) NOT NULL DEFAULT '' COMMENT '交易货币_结算货币,方便查询',
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '需要买入或卖出的币种，作为货物',
  `settlement_currency` varchar(8) NOT NULL COMMENT '用于结算的货币，一般是平台的基本货币',
  `fee_coin` decimal(12,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '交易已经产生的币种(获取)费用比例，对于买入：收入的币中少了这个比例的数量，对于卖出：没损失',
  `fee_currency` decimal(12,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '交易已经产生的结算货币费用，对于买入：没损失，对于卖出：按成交价格收入的总结算货币中少了成交价*这个比例',
  `fee_coin_user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '在该市场扣除的数字货币的费用将会转移到这个用户上面',
  `fee_currency_user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '在该市场扣除的结算货币的费用将会转移到这个用户上面',
  `on_market_time` datetime DEFAULT NULL COMMENT '市场启用的时间，主要是日期，说明该市场从什么时候开始上市',
  `day_exchange_begin` time DEFAULT NULL COMMENT '每天交易开始时间',
  `day_exchange_end` time DEFAULT NULL COMMENT '每天交易结束时间',
  `last_day_price` decimal(24,8) unsigned DEFAULT '0.00000000' COMMENT '昨天交易金额，收盘价',
  `max_increase` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '最大涨幅，按照百分比计算，这里是*100后的结果',
  `min_decrease` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '最大跌幅，按照百分比计算，这里是*100后的结果',
  `min_exchange_num` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '每次最小下单的数量',
  `max_exchange_num` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '每次最大下单的数量',
  `closed` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否关闭交易，0表示市场开放，1表示关闭交易',
  `create_time` datetime NOT NULL COMMENT '市场创建时间',
  `last_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `coin_url` varchar(256) DEFAULT NULL COMMENT '买入卖出币的图标',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_market_coin_current` (`coin_name`,`settlement_currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定义交易市场的一些参数';

#
# Structure for table "t_market_group_config"
#

CREATE TABLE `t_market_group_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `market_id` int(11) NOT NULL COMMENT '配对对应的交易对Id',
  `group_id` int(11) NOT NULL COMMENT '对应的用户分组id',
  `buy_con_value` varchar(20) DEFAULT '0' COMMENT '收取的手续费',
  `remark` varchar(50) DEFAULT NULL COMMENT '备注',
  `sell_con_value` varchar(20) DEFAULT '0' COMMENT '卖出的费率',
  `coin_name` varchar(20) DEFAULT NULL COMMENT '卖出的币种名字',
  `settlement_currency` varchar(20) DEFAULT NULL COMMENT '兑换的货币币种',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_merchant"
#

CREATE TABLE `t_merchant` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '所属的用户id',
  `name` varchar(50) NOT NULL COMMENT '商人/兑换商显示名称',
  `phone` varchar(20) NOT NULL DEFAULT '' COMMENT '电话',
  `email` varchar(50) DEFAULT NULL COMMENT '商人/兑换商对外暴露的邮箱',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '兑换商类型，1：普通兑换商，2：超级兑换商',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态，0：正常，1：已经禁用 2:审核中3:审核失败',
  `working_status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '工作状态（表示兑换商自己是否接单），1：正常工作，0：不工作不接单',
  `bank_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '银行类型，0：普通银行，1：支付宝，2：微信支付',
  `bank_user` varchar(32) DEFAULT NULL COMMENT '兑换商银行账户名',
  `bank_name` varchar(40) DEFAULT NULL COMMENT '兑换商银行名称',
  `bank_no` varchar(50) DEFAULT NULL COMMENT '兑换商银行卡号码',
  `add_time` int(11) NOT NULL COMMENT '创建时间',
  `reason` varchar(255) DEFAULT NULL COMMENT '失败原因',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `fk_merchant_user_id_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商人/兑换商基本信息表';

#
# Structure for table "t_merchant_bill"
#

CREATE TABLE `t_merchant_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` int(11) unsigned NOT NULL,
  `coin_name` varchar(8) DEFAULT NULL COMMENT '变化的币种名称，缩写，编译查看',
  `sub_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '子类型，0：该币种的正常的余额变化，1：表示是该币种冻结金变化',
  `reason` varchar(8) NOT NULL COMMENT '资金变化原因，比如received:收到尾部转入，send:转出等',
  `change_amount` decimal(32,8) DEFAULT NULL COMMENT ' 变化大小，正数表示增加金额，负数表示减少金额',
  `comment` varchar(100) DEFAULT NULL COMMENT '备注信息，记录一些额外信息，比如变化的订单号等',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_user_bill_merchant_id_idx` (`merchant_id`),
  KEY `last_time` (`last_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='兑换商账单，记录所有用户所有资产的变化记录';

#
# Structure for table "t_merchant_coin"
#

CREATE TABLE `t_merchant_coin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` int(11) unsigned NOT NULL COMMENT '用户id',
  `coin_name` varchar(8) NOT NULL COMMENT '币种名称',
  `available_balance` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '可用资产',
  `freeze_balance` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '冻结的资产',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '用户币种状态，0：正常，1：冻结使用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_user_coin` (`merchant_id`,`coin_name`),
  CONSTRAINT `fk_merchant_id` FOREIGN KEY (`merchant_id`) REFERENCES `t_merchant` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='兑换商的币种资产';

#
# Structure for table "t_merchant_coin_conf"
#

CREATE TABLE `t_merchant_coin_conf` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '币种名称',
  `cny_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '人民币价格',
  `dollar_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '美元价格',
  `hkdollar_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '港币价格',
  `order_min_amount` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '该币种最小能买卖的个数',
  `order_max_amount` decimal(24,8) unsigned NOT NULL DEFAULT '9999999999999.00000000' COMMENT '该币种最大能买卖的个数',
  `fee_rate` decimal(6,4) unsigned NOT NULL DEFAULT '0.0000' COMMENT '费率，必须小于1,0.2表示20%',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '0表示正常，1表示禁用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `coin_name` (`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='支持兑换商兑换的币种';

#
# Structure for table "t_mining_stat"
#

CREATE TABLE `t_mining_stat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stat_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '统计时间，统计的时候所在那天的整天数据',
  `trade_bonus` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '今天总的交易（挖矿）直接奖励数(不包括推荐)，奖励是统计时间的下一天到账的',
  `trade_rec_bonus` decimal(32,8) unsigned DEFAULT NULL COMMENT '今天总的交易推荐（挖矿推荐）奖励数，奖励是统计时间的下一天到账的',
  `other_bonus` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '今天内其他平台币奖励总和（注册和推荐赠送）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `stat_time` (`stat_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='挖矿奖励统计，每天统计一次';

#
# Structure for table "t_national_code"
#

CREATE TABLE `t_national_code` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `national_name` varchar(50) DEFAULT NULL,
  `chinese_name` varchar(50) DEFAULT NULL,
  `abbre` varchar(10) DEFAULT NULL,
  `code` varchar(20) DEFAULT NULL,
  `land` varchar(255) DEFAULT NULL,
  `price` decimal(10,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Structure for table "t_order_complaint"
#

CREATE TABLE `t_order_complaint` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `order_id` int(11) unsigned NOT NULL COMMENT '订单id',
  `type` int(1) unsigned NOT NULL COMMENT '申诉类型，1：用户申诉，2：兑换商申诉',
  `credential_urls` varchar(560) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付凭证的图片链接',
  `credential_comment` varchar(400) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '上传支付凭证的说明',
  `status` int(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态，0：申诉中，1：已完成',
  `add_time` int(11) unsigned NOT NULL COMMENT '创建时间',
  `finish_time` int(11) DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (`id`),
  KEY `fk_order_comp_user_id_idx` (`user_id`),
  KEY `fk_order_comp_order_id_idx` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='订单申诉，一般对于长时间挂起的订单';

#
# Structure for table "t_otc"
#

CREATE TABLE `t_otc` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `user_name` varchar(32) DEFAULT NULL COMMENT '用户名',
  `appl_no` varchar(64) DEFAULT NULL COMMENT '编号',
  `type` int(11) NOT NULL COMMENT '1买2卖',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态',
  `coin_name` varchar(10) NOT NULL COMMENT '币名',
  `legal_name` varchar(10) DEFAULT 'cny' COMMENT '法币',
  `amount` decimal(32,8) DEFAULT '0.00000000' COMMENT '剩余数',
  `price` decimal(32,8) DEFAULT '0.00000000' COMMENT '价格',
  `fee_rate` decimal(32,8) DEFAULT '0.00000000' COMMENT '提现手续费比例',
  `fee` decimal(32,8) DEFAULT '0.00000000' COMMENT '手续费(总的手续费)',
  `amount_frozen` decimal(32,8) DEFAULT '0.00000000' COMMENT '冻结数(匹配后的),正在转移流程的数量',
  `amount_success` decimal(32,8) DEFAULT '0.00000000' COMMENT '交易成功的数量',
  `amount_all` decimal(32,8) DEFAULT '0.00000000' COMMENT '挂单总数',
  `comment` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `min_amount` decimal(32,8) DEFAULT '0.00000000' COMMENT '每笔挂单限额最小',
  `max_amount` decimal(32,8) DEFAULT '0.00000000' COMMENT '每笔挂单限额最大',
  PRIMARY KEY (`id`),
  KEY `idx_user_id_type_status` (`user_id`,`status`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='c2c交易申请（场外交易，法币交易）';

#
# Structure for table "t_otc_bill"
#

CREATE TABLE `t_otc_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `coin_name` varchar(10) NOT NULL COMMENT '币种',
  `type` int(11) NOT NULL COMMENT '类型',
  `amount` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '数量',
  `price` decimal(32,8) DEFAULT '0.00000000' COMMENT '价格',
  `fee` decimal(32,8) DEFAULT '0.00000000' COMMENT '手续费',
  `order_no` varchar(64) NOT NULL COMMENT '对应关联的交易编号',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_userid_coinname_type` (`user_id`,`coin_name`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='法币交易清单';

#
# Structure for table "t_otc_kline"
#

CREATE TABLE `t_otc_kline` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(10) DEFAULT NULL COMMENT '币种',
  `legal_name` varchar(10) DEFAULT 'cny' COMMENT '法币',
  `open_price` decimal(32,8) DEFAULT NULL COMMENT '开盘价',
  `close_price` decimal(32,8) DEFAULT NULL COMMENT '收盘价',
  `high_price` decimal(32,8) DEFAULT NULL COMMENT '最高价',
  `low_price` decimal(32,8) DEFAULT NULL COMMENT '最低价',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='法币交易统计信息';

#
# Structure for table "t_otc_market"
#

CREATE TABLE `t_otc_market` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(50) NOT NULL DEFAULT '0' COMMENT '交易币种',
  `legal_name` varchar(50) NOT NULL DEFAULT 'cny' COMMENT '交易法币，默认cny(人民币)',
  `last_price` decimal(24,8) NOT NULL COMMENT '最新成交价',
  `min_exchange_num` decimal(24,8) NOT NULL COMMENT '每次最小下单的数量',
  `max_exchange_num` decimal(24,8) NOT NULL COMMENT '每次最大下单的数量',
  `status` tinyint(4) NOT NULL COMMENT '0：开启，1：关闭',
  `create_time` datetime NOT NULL COMMENT '市场创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `fee_rate` decimal(24,8) DEFAULT NULL COMMENT '卖家挂单手续费',
  `expired_time_cancel` int(11) DEFAULT NULL COMMENT '超时取消(分钟)',
  `expired_time_freeze` int(11) DEFAULT NULL COMMENT '超时冻结(分钟)',
  `max_appl_buy_count` int(11) DEFAULT '10' COMMENT '最大挂单数(买单)',
  `max_appl_sell_count` int(11) DEFAULT '10' COMMENT '最大挂单数(卖单)',
  PRIMARY KEY (`id`),
  KEY `coin` (`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='c2c交易市场信息及配置';

#
# Structure for table "t_otc_order"
#

CREATE TABLE `t_otc_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(64) DEFAULT NULL COMMENT '编号',
  `deposit_application_id` bigint(20) DEFAULT NULL COMMENT '充值挂单ID',
  `withdrawal_application_id` bigint(20) DEFAULT NULL COMMENT '提现挂单ID',
  `deposit_user_id` int(11) DEFAULT NULL COMMENT '充值用户ID',
  `withdrawal_user_id` int(11) DEFAULT NULL COMMENT '提现用户ID',
  `deposit_user_name` varchar(32) DEFAULT NULL COMMENT '充值用户名',
  `withdrawal_user_name` varchar(32) DEFAULT NULL COMMENT '提现用户名',
  `status` int(11) DEFAULT NULL COMMENT '状态',
  `coin_name` varchar(10) DEFAULT NULL COMMENT '币名',
  `legal_name` varchar(10) DEFAULT NULL COMMENT '法币',
  `price` decimal(32,8) DEFAULT NULL COMMENT '价格',
  `amount` decimal(32,8) DEFAULT NULL COMMENT '数量',
  `fee_rate` decimal(32,8) DEFAULT NULL COMMENT '手续费率',
  `withdrawal_desc` varchar(256) DEFAULT NULL COMMENT '提现描述',
  `deposit_desc` varchar(256) DEFAULT NULL COMMENT '充值描述',
  `credential_comment` varchar(256) DEFAULT NULL COMMENT '凭证说明',
  `credential_urls` varchar(1024) DEFAULT NULL COMMENT '凭证图片',
  `cancel_desc` varchar(256) DEFAULT NULL COMMENT '取消说明',
  `appeal_role` int(11) DEFAULT NULL COMMENT '申诉人1：买家，2：卖家',
  `appeal_code` varchar(50) DEFAULT NULL COMMENT '申诉号',
  `appeal_desc` varchar(256) DEFAULT NULL COMMENT '申诉说明',
  `remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `accept_time` datetime DEFAULT NULL COMMENT '接单时间',
  `upload_credential_time` datetime DEFAULT NULL COMMENT '上传凭证时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `expire_time` datetime DEFAULT NULL COMMENT '超时时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `pay_type` int(11) DEFAULT NULL COMMENT '支付方式(0银行卡，1支付宝，2微信)',
  `create_id` int(11) DEFAULT NULL COMMENT '从市场上购买者ID（取消订单时有用）',
  PRIMARY KEY (`id`),
  KEY `idx_deposit_appl_id` (`deposit_application_id`),
  KEY `idx_withdraw_appl_id` (`withdrawal_application_id`),
  KEY `idx_userid_status_createtime` (`deposit_user_id`,`withdrawal_user_id`,`status`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='c2c（场外交易，法币交易）交易匹配';

#
# Structure for table "t_otc_pay"
#

CREATE TABLE `t_otc_pay` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `bank_type` int(11) NOT NULL COMMENT '银行类型，0：普通银行，1：支付宝，2：微信支付',
  `bank_name` varchar(64) NOT NULL COMMENT '收款银行名称,支付宝，微信',
  `bank_user` varchar(64) NOT NULL COMMENT '收款的银行账户名/支付宝等账户名(姓名)',
  `bank_no` varchar(64) NOT NULL COMMENT '收款银行卡号码/支付宝/微信等',
  `order_id` bigint(20) NOT NULL COMMENT '对应的订单号',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_otc_stat"
#

CREATE TABLE `t_otc_stat` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `coin_name` varchar(10) NOT NULL COMMENT '币名',
  `legal_name` varchar(10) DEFAULT 'cny' COMMENT '法币',
  `amount_pass` decimal(32,8) DEFAULT '0.00000000' COMMENT '交易成功数额',
  `amount_fail` decimal(32,8) DEFAULT '0.00000000' COMMENT '交易失败数额',
  `trade_pass` int(11) DEFAULT '0' COMMENT '交易成功笔数',
  `trade_fail` int(11) DEFAULT '0' COMMENT '交易失败笔数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_userid_coinname` (`user_id`,`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_received_coin"
#

CREATE TABLE `t_received_coin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '收到钱的用户id',
  `address` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '收到转账的地址',
  `coin_name` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '币种名称',
  `txid` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '转账的交易id',
  `amount` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '收到外部的金额大小',
  `fee` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '转入收取的费用，最后到账的金额是amount-fee',
  `tx_time` int(11) unsigned DEFAULT NULL COMMENT '交易时间，是交易产生的时间，一般是区块链区块的时间',
  `received_time` int(11) unsigned DEFAULT NULL COMMENT '收到的时间，一般是记录创建时间',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态，1：已经收到',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_coin_txid` (`coin_name`,`txid`),
  KEY `fk_received_user_id_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='收到外部转入的记录';

#
# Structure for table "t_send_coin"
#

CREATE TABLE `t_send_coin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '转出钱的用户id',
  `received_user_id` int(11) unsigned DEFAULT NULL COMMENT '收款的用户id，只有在内部转账的时候才会有',
  `address` varchar(64) NOT NULL COMMENT '收款的地址',
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '币种名称',
  `txid` varchar(100) DEFAULT '' COMMENT '转账的交易id',
  `amount` decimal(20,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '转账外部的金额大小',
  `fee` decimal(20,8) unsigned DEFAULT NULL COMMENT '转账费用',
  `send_time` datetime NOT NULL COMMENT '发送的时间，一般是记录创建时间',
  `status` int(11) DEFAULT '0' COMMENT '状态，1：已经成功发出,0待审批，2审核失败',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `second_status` int(11) DEFAULT '0' COMMENT '此状态和第一次状态关联（0,1）：表示第一审核通过，第二次待审核；（1,0）表示内部转账审核通过；（1,1）：表示第二次审核通过；（2:1）：表示第二次审核拒绝 （2:0）：表示内部转账审核失败',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_coin_txid` (`coin_name`,`txid`),
  KEY `fk_send_coin_user_id_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发送到外部的转出记录';

#
# Structure for table "t_server_config"
#

CREATE TABLE `t_server_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `server_type` varchar(20) DEFAULT NULL COMMENT '服务器类型：1.交易服 2.运营后台服务器 3.数据库服。4撮合服务器 5.',
  `server_inner_address` varchar(20) DEFAULT NULL COMMENT '服务器内部ip',
  `server_external_address` varchar(20) DEFAULT NULL COMMENT '服务器外部地址',
  `server_name` varchar(20) DEFAULT NULL COMMENT '服务器名',
  `port` varchar(20) DEFAULT NULL COMMENT '服务端口',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_share_out_bonus_log"
#

CREATE TABLE `t_share_out_bonus_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `coin_name` varchar(12) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '赠送的币种名称（分红币种）',
  `user_base_coin` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '分红时用户所持有的平台币个数',
  `user_bonus` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '分红的数量（coin_name字段中的币种）',
  `create_time` datetime DEFAULT NULL COMMENT '分红时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='分红详细日志';

#
# Structure for table "t_sms_captcha"
#

CREATE TABLE `t_sms_captcha` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `mobile` varchar(128) NOT NULL COMMENT '手机号',
  `type` varchar(6) DEFAULT NULL COMMENT '验证码:01注册,02忘记密码,03设置交易,04修改交易，05更换手机号',
  `code` varchar(6) DEFAULT NULL COMMENT '验证码',
  `status` int(11) DEFAULT '0' COMMENT '0未验证，1已经验证',
  `lastTime` datetime DEFAULT NULL COMMENT '短信验证码15分钟有效',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mobile` (`mobile`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Structure for table "t_super_merchant_order"
#

CREATE TABLE `t_super_merchant_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '订单号，创建订单的时候自动生成',
  `type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单类型，1：充值/买入，2：提现/卖出',
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '需要买入或卖出的币种，目前固定为平台的基本货币',
  `merchant_id` int(11) unsigned NOT NULL COMMENT '下单的用户',
  `super_merchant_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '接单的超级兑换商id，0表示没有人接单',
  `amount` decimal(20,8) unsigned NOT NULL COMMENT '需要充值或提现的总量',
  `settlement_currency` varchar(8) NOT NULL DEFAULT '' COMMENT '用于结算的货币，一般是CNY或USD',
  `price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '下单时价格',
  `add_time` int(11) unsigned NOT NULL COMMENT '订单创建时间',
  `accept_time` int(11) unsigned DEFAULT NULL COMMENT '接单时间',
  `proof_time` int(11) unsigned DEFAULT NULL COMMENT '上传凭证时间',
  `finish_time` int(11) unsigned DEFAULT NULL COMMENT '结束时间，是订单完成或者取消的时间',
  `fee` decimal(20,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '产生的费用，对于充值（买），最后用户收入是amount-fee,对于提现（卖），最后兑换商收入是amount-fee，只有在最后成交的时候才会扣费用',
  `status` int(3) unsigned NOT NULL COMMENT '状态状态1已完成;2待接单,3待付款,4待收款,5,申诉中100已取消',
  `credential_urls` varchar(560) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付凭证的图片链接',
  `credential_comment` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '上传支付凭证的说明',
  `bank_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '银行类型，0：普通银行，1：支付宝，2：微信支付',
  `bank_user` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收款的银行账户名',
  `bank_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收款银行名称',
  `bank_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收款银行卡号码',
  `cancel_type` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '取消类型，缩写，只有状态为取消才有意义',
  `cancel_comment` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '取消的时候输入的备注信息',
  `remake` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '下单时备注信息',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no_UNIQUE` (`order_no`),
  KEY `fk_order_merchant_id_idx` (`merchant_id`),
  KEY `fk_order_super_merchant_id_idx` (`super_merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='由兑换商向超级兑换商发起的订单，超级兑换商买卖平台货币';

#
# Structure for table "t_task_server"
#

CREATE TABLE `t_task_server` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `task_name` varchar(45) NOT NULL DEFAULT '' COMMENT '后台任务名称',
  `server_address` varchar(45) NOT NULL COMMENT '进行该工作的服务器地址',
  `last_update_time` int(11) unsigned NOT NULL COMMENT '最近一次检测的时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `task_name_UNIQUE` (`task_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务服务器的筛选表，用来确定某个后台任务是由哪个服务器来进行，比如说某个任务服务器的更新心跳是1分钟，如果超过3分钟没有更新时间，那么其他服务器将会取代该服务器';

#
# Structure for table "t_time_monitoring"
#

CREATE TABLE `t_time_monitoring` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `monitoring_type` varchar(50) NOT NULL COMMENT '监控的类型',
  `monitoring_name` varchar(50) NOT NULL COMMENT '监控的名字:：挂单监控，买入监控，卖出监控等',
  `num_minutes` int(11) NOT NULL DEFAULT '5' COMMENT '刷新时间间隔，以分钟为单位',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_time_monitoring_config"
#

CREATE TABLE `t_time_monitoring_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `monitoring_type` varchar(30) NOT NULL COMMENT '监控类型',
  `coin_name` varchar(50) NOT NULL COMMENT '需要买入或卖出的币种，作为货物',
  `num_minutes` int(10) NOT NULL DEFAULT '5' COMMENT '几分钟刷新一次，默认五分钟一次',
  `settlement_currency` varchar(50) NOT NULL COMMENT '用于结算的货币，一般是平台的基本货币',
  `buy_number` int(10) DEFAULT NULL COMMENT '买入次数',
  `sell_number` int(10) DEFAULT NULL COMMENT '卖出次数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_trade"
#

CREATE TABLE `t_trade` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '需要买入或卖出的币种，作为货物',
  `settlement_currency` varchar(8) NOT NULL COMMENT '用于结算的货币，一般是平台的基本货币',
  `price` decimal(20,8) unsigned NOT NULL COMMENT '购买或卖出币种的单价，就是买入或卖出1个coin_name所对应的结算货币的个数',
  `amount` decimal(20,8) unsigned NOT NULL COMMENT '卖出或卖出币种/货物的总数量',
  `total_currency` decimal(24,8) unsigned NOT NULL COMMENT '对于买入：提供的总费用（冻结），对于卖出：期待获取的总金额，等于price*amount,属于冗余字段',
  `type` tinyint(1) unsigned NOT NULL COMMENT '买入卖出类型，1：买入，2：卖出',
  `price_type` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '限价类型，0限价交易，1市价交易',
  `deal_coin` decimal(20,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '已经成交的币(货物)数量',
  `deal_currency` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '已经成交的结算货币数量，对于买入：已经花费的结算货币，对于卖出：已经赚取的结算货币数量（包括费用)',
  `fee_coin` decimal(20,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '交易已经产生的币种(获取)费用，对于买入：按成交价格收入的币中少了这个数量，对于卖出：没损失',
  `fee_currency` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '交易已经产生的结算货币费用，对于买入：没损失，对于卖出：按成交价格收入的总结算货币中少了这个数量',
  `add_time` int(11) unsigned NOT NULL COMMENT '创建交易的时间',
  `last_trade_time` int(11) unsigned DEFAULT NULL COMMENT '最后一次成交的时间，如果是全部成交，就是交易结束的时间',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态，0：正常交易中，1：全部成交，2：交易已经取消',
  PRIMARY KEY (`id`),
  KEY `fk_trade_user_id_idx` (`user_id`),
  KEY `index_getMatchSellTrade` (`status`,`type`,`price`) COMMENT '匹配条件的卖出的单'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易请求';

#
# Structure for table "t_trade_bonus_log"
#

CREATE TABLE `t_trade_bonus_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `coin_name` varchar(12) NOT NULL DEFAULT '' COMMENT '交易币种',
  `settlement_currency` varchar(12) NOT NULL DEFAULT '' COMMENT '结算货币',
  `trade_log_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '交易的id',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '类型，1买入，2卖出',
  `trade_fee` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '交易产生的手续费，对于买入，这里说的是交易币种，对于卖出，这里是结算货币',
  `recommend_user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '推荐用户id',
  `trade_bonus` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '交易奖励（挖矿返佣）',
  `recommend_bonus` decimal(24,8) unsigned DEFAULT NULL COMMENT '推荐人拿到的奖励',
  `create_time` datetime DEFAULT NULL COMMENT '奖励/返佣时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `recommend_user_id` (`recommend_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='挖矿返佣日志';

#
# Structure for table "t_trade_log"
#

CREATE TABLE `t_trade_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '需要买入或卖出的币种，作为货物',
  `settlement_currency` varchar(8) NOT NULL COMMENT '用于结算的货币，一般是平台的基本货币',
  `price` decimal(20,8) unsigned NOT NULL COMMENT '购买或卖出币种的单价，就是买入或卖出1个coin_name所对应的结算货币的个数',
  `amount` decimal(20,8) unsigned NOT NULL COMMENT '本次交易卖出或卖出币种/货物的数量',
  `buy_user_id` int(11) unsigned NOT NULL COMMENT '买房用户id',
  `sell_user_id` int(11) unsigned NOT NULL COMMENT '卖方用户id',
  `add_time` int(11) unsigned NOT NULL COMMENT '交易发生的时间',
  `buy_fee_coin` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '本次交易产生买入费用，因为买入收入的是币（货物），所以这里是币的数量，买入方最后收入是amount-fee_buy',
  `sell_fee_currency` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '本次交易产生卖出费用，因为卖出收入的是结算货币，所以这里是结算货币的数量，卖入方最后收入是price*amount-fee_sell',
  `buy_trade_id` int(11) unsigned NOT NULL COMMENT '买方的t_trade表中的交易请求id',
  `sell_trade_id` int(11) unsigned NOT NULL COMMENT '卖方的t_trade表中的交易请求id',
  PRIMARY KEY (`id`),
  KEY `fk_buy_trade_id_idx` (`buy_trade_id`),
  KEY `fk_sell_trade_id_idx` (`sell_trade_id`),
  KEY `index_buy_user_id` (`buy_user_id`),
  KEY `index_sell_user_id` (`sell_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易日志，所有的交易都在这个表里面记录，这个表所有记录都来源于t_trade表的变化';

#
# Structure for table "t_trade_no_warning_user"
#

CREATE TABLE `t_trade_no_warning_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_name` varchar(20) DEFAULT NULL COMMENT '用户名',
  `user_id` int(11) DEFAULT NULL COMMENT '用户id',
  `create_time` datetime NOT NULL,
  `no_warning_type` varchar(50) NOT NULL DEFAULT '1' COMMENT '警告的交易类型',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_trade_stat"
#

CREATE TABLE `t_trade_stat` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `stat_time` int(11) unsigned NOT NULL COMMENT '统计时间',
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '需要买入或卖出的币种，作为货物',
  `settlement_currency` varchar(8) NOT NULL COMMENT '用于结算的货币，一般是平台的基本货币',
  `stat_cycle` smallint(5) unsigned NOT NULL COMMENT '统计周期，分钟为单位，有1,5,15,30,60,1440',
  `order_times` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '下单次数',
  `order_amount` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '下单总额',
  `order_total_currency` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '下订单总结算货币',
  `order_user_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '下单总用户数',
  `deal_times` int(11) unsigned NOT NULL COMMENT '成交总次数',
  `deal_amount` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '成交总额',
  `deal_total_currency` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '成交总结算货币金额',
  `fee_amount` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '产生的数字货币费用总额',
  `fee_total_currency` decimal(32,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '产生的结算货币费用总额',
  `deal_min_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '成交的最小价格',
  `deal_max_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '成交的最高价格',
  `deal_first_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '第一单价格，就是开盘价格',
  `deal_last_price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '最后一单价格，就是收盘价格',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_stat_time_cycle` (`stat_time`,`stat_cycle`,`coin_name`,`settlement_currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='周期交易数量统计';

#
# Structure for table "t_trade_warning"
#

CREATE TABLE `t_trade_warning` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `remark` varchar(500) DEFAULT NULL COMMENT '警报详情',
  `amount` decimal(18,8) NOT NULL DEFAULT '0.00000000' COMMENT '数量（钱的数量，币的数量）',
  `market_id` int(11) NOT NULL COMMENT '对应的交易对Id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Structure for table "t_trade_warning_detail"
#

CREATE TABLE `t_trade_warning_detail` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` int(11) NOT NULL COMMENT '用户id',
  `creat_time` datetime DEFAULT NULL COMMENT '创建时间',
  `sure_type` int(5) NOT NULL DEFAULT '0' COMMENT '是否确认：0：待确认 1：已经确认 2：拒绝 3.其他',
  `trade_warning_id` int(11) NOT NULL COMMENT '对应报警配置表Id',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `trade_log_id` bigint(20) NOT NULL COMMENT '对应的交易订单Id',
  `warning_type` varchar(50) NOT NULL DEFAULT '' COMMENT '对应的警告类型',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Structure for table "t_transfer_address"
#

CREATE TABLE `t_transfer_address` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '转账地址所属的用户id',
  `coin_name` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '币种名称',
  `address` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '用户对应币种的转出地址',
  `name` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '地址的名称，便于记忆',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态，0表示正常，1表示禁用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次修改时间',
  PRIMARY KEY (`id`),
  KEY `fk_transfer_address_user_id_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='转账地址管理';

#
# Structure for table "t_transfer_coin_config"
#

CREATE TABLE `t_transfer_coin_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `coin_name` varchar(255) NOT NULL COMMENT '币种名称',
  `transfer_in_number` int(20) DEFAULT NULL COMMENT '转入的数量',
  `transfer_out_number` int(20) DEFAULT NULL COMMENT '转出',
  `refresh_time` int(11) DEFAULT NULL COMMENT '刷新的时间间隔',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_user"
#

CREATE TABLE `t_user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_name` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '用户登录名称，全表唯一',
  `nick_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户昵称',
  `area_code` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '手机国家代码',
  `mobile` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户绑定的手机号码',
  `password` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `salt` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '密码盐',
  `invite_code` char(10) COLLATE utf8mb4_bin NOT NULL COMMENT '邀请码',
  `referrer` int(11) DEFAULT NULL COMMENT '邀请人id',
  `pay_password` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付密码',
  `pay_salt` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付密码盐',
  `real_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户真实姓名',
  `id_card_type` int(11) DEFAULT NULL COMMENT '实名验证的证件类型，0是默认表示没有认真，1表示中国居民身份证，2是国际护照',
  `id_card` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '实名验证的证件号码',
  `real_name_status` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '实名验证状态，0，未实名验证，1，等待身份证验证，2：身份证号码验证通过',
  `id_card_img1` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '实名验证的图片1',
  `id_card_img2` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '实名验证的图片2',
  `id_card_img3` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '实名验证的图片3',
  `id_card_info` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '当前实名验证的一些额外备注信息，比如验证失败原因',
  `login_times` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户登录次数',
  `register_ip` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '注册时的ip',
  `last_login_ip` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '最近一次登录的用户ip',
  `register_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `last_login_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后一次登录时间',
  `status` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '用户状态，0：正常，1：被禁用',
  `email` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '邮箱',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次用户修改资料的时间，登录不修改这个时间',
  `id_card_status` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '图片实名验证的状态，0：没有实名验证通过，1： 已经实名验证通过，2：已经提交实名验证，待验证，3：实名验证失败，退回用户重新提交',
  `id_card_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '图片实名认证时间',
  `group_type` varchar(20) COLLATE utf8mb4_bin NOT NULL DEFAULT 'GROUP_TYPE_BASE' COMMENT 'GROUP_TYPE_BASE:无属性 ，A ,B,C,D',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mobile` (`mobile`),
  UNIQUE KEY `idx_email` (`email`),
  KEY `idx_area_mobile` (`area_code`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='用户的基本信息';

#
# Structure for table "t_user_api"
#

CREATE TABLE `t_user_api` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户id',
  `api_key` varchar(64) NOT NULL COMMENT 'api key用来区分是哪个用户调用了请求',
  `api_secret` varchar(64) NOT NULL COMMENT 'api secret，用来签名请求',
  `white_ip_list` varchar(128) DEFAULT NULL COMMENT 'ip白名单，逗号分隔',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'api状态，0：禁用，1：审核通过 2: 审核不通过，3 审核中',
  `comment` varchar(64) DEFAULT NULL COMMENT '这个api的说明，一个用户可以加多个api',
  `create_time` datetime NOT NULL COMMENT '记录增加的时间',
  `expired_time` datetime DEFAULT NULL COMMENT '过期时间',
  `last_time` datetime NOT NULL COMMENT '记录修改的时间',
  PRIMARY KEY (`id`),
  KEY `index_user` (`user_id`),
  KEY `index_api_key` (`api_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户的API参数配置';

#
# Structure for table "t_user_bank"
#

CREATE TABLE `t_user_bank` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `name` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '用户定义的名称，用于记忆',
  `bank_type` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '银行类型，0：普通银行，1：支付宝，2：微信支付',
  `legal_name` varchar(8) COLLATE utf8mb4_bin NOT NULL COMMENT '法币名称',
  `bank_name` varchar(40) COLLATE utf8mb4_bin NOT NULL COMMENT '收款银行名称,支付宝，微信',
  `bank_user` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '收款的银行账户名/支付宝等账户名(姓名)',
  `bank_no` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '收款银行卡号码/支付宝/微信等',
  `status` int(11) DEFAULT '1' COMMENT '1开启，0关闭',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `has_bind` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否绑定银行卡 0 否 1 是',
  `receipt_code` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收款码（银行卡没有）',
  PRIMARY KEY (`id`),
  KEY `fk_user_bank_user_id_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='用户自定义的银行信息，用于提现';

#
# Structure for table "t_user_bill"
#

CREATE TABLE `t_user_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `coin_name` varchar(8) DEFAULT NULL COMMENT '变化的币种名称，缩写，编译查看',
  `sub_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '子类型，0：该币种的正常的余额变化，1：表示是该币种冻结金变化',
  `reason` varchar(8) NOT NULL COMMENT '资金变化原因，比如received:收到尾部转入，send:转出等',
  `change_amount` decimal(32,8) DEFAULT NULL COMMENT ' 变化大小，正数表示增加金额，负数表示减少金额',
  `comment` varchar(100) DEFAULT NULL COMMENT '备注信息，记录一些额外信息，比如变化的订单号等',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_user_bill_user_id_idx` (`user_id`),
  KEY `last_time` (`last_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户账单，记录所有用户所有资产的变化记录';

#
# Structure for table "t_user_chat_key"
#

CREATE TABLE `t_user_chat_key` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL COMMENT '用户id',
  `key` varchar(256) DEFAULT NULL COMMENT '聊天key',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间，冗余设计',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Structure for table "t_user_chat_log"
#

CREATE TABLE `t_user_chat_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from_user_id` int(11) NOT NULL COMMENT '发送者id',
  `to_user_id` int(11) NOT NULL COMMENT '接收者id',
  `object_name` varchar(50) NOT NULL COMMENT '消息类型',
  `content` text NOT NULL COMMENT '消息',
  `extra` varchar(256) DEFAULT NULL COMMENT '附加消息',
  `channel_type` varchar(50) NOT NULL COMMENT '会话类型',
  `msg_time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间戳',
  `msg_uid` varchar(256) NOT NULL COMMENT '消息唯一标识',
  `sensitive_type` tinyint(4) NOT NULL COMMENT '消息中是否含有敏感词标识，0 为不含有敏感词，1 为含有屏蔽敏感词，2 为含有替换敏感词',
  `source` varchar(50) NOT NULL COMMENT '消息发送源',
  PRIMARY KEY (`id`),
  KEY `view` (`from_user_id`,`to_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户聊天记录';

#
# Structure for table "t_user_coin"
#

CREATE TABLE `t_user_coin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户id',
  `coin_name` varchar(8) COLLATE utf8mb4_estonian_ci NOT NULL COMMENT '币种名称',
  `bind_address` varchar(64) COLLATE utf8mb4_estonian_ci DEFAULT NULL COMMENT '地址',
  `available_balance` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '可用资产',
  `freeze_balance` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '冻结的资产',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '用户币种状态，0：正常，1：冻结使用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_user_coin` (`user_id`,`coin_name`),
  KEY `index_coin_address` (`coin_name`,`bind_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_estonian_ci COMMENT='用户的币种资产';

#
# Structure for table "t_user_group_config"
#

CREATE TABLE `t_user_group_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_type` varchar(20) NOT NULL DEFAULT '0' COMMENT '0:表示默认属性 A,B,C,D',
  `group_name` varchar(20) DEFAULT NULL COMMENT '名字',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '0:表示未禁用 1.表示禁用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_user_log"
#

CREATE TABLE `t_user_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `type` varchar(12) NOT NULL COMMENT '用户操作类型',
  `operation_time` datetime NOT NULL COMMENT '操作的时间',
  `operation_ip` varchar(16) DEFAULT NULL COMMENT '用户操作的ip',
  `used_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '花费时间，单位是毫秒',
  `success` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '操作是否成功，0是失败，1是成功',
  `comment` varchar(500) DEFAULT NULL COMMENT '用户操作时提供的参数',
  PRIMARY KEY (`id`),
  KEY `fk_user_log_user_id_idx` (`user_id`),
  KEY `user_log_op_time` (`operation_time`),
  CONSTRAINT `fk_user_log_user_id` FOREIGN KEY (`user_id`) REFERENCES `t_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户日志，用户涉及到修改的接口都要记录日志';

#
# Structure for table "t_user_merchant_order"
#

CREATE TABLE `t_user_merchant_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(20) NOT NULL COMMENT '订单号，创建订单的时候自动生成',
  `type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单类型，1：充值/买入，2：提现/卖出',
  `coin_name` varchar(8) NOT NULL COMMENT '需要买入或卖出的币种，目前固定为平台的基本货币',
  `user_id` int(11) unsigned NOT NULL COMMENT '下单的用户',
  `merchant_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '接单的兑换商id，0表示没有人接单',
  `amount` decimal(20,8) unsigned NOT NULL COMMENT '需要充值或提现的总量',
  `settlement_currency` varchar(8) NOT NULL COMMENT '用于结算的货币，一般是CNY或USD',
  `price` decimal(24,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '下单时价格',
  `add_time` int(11) unsigned NOT NULL COMMENT '订单创建时间',
  `accept_time` int(11) unsigned DEFAULT NULL COMMENT '接单时间',
  `proof_time` int(11) unsigned DEFAULT NULL COMMENT '上传凭证时间',
  `finish_time` int(11) unsigned DEFAULT NULL COMMENT '结束时间，是订单完成或者取消的时间',
  `fee` decimal(20,8) unsigned NOT NULL DEFAULT '0.00000000' COMMENT '产生的费用，对于充值（买），最后用户收入是amount-fee,对于提现（卖），最后兑换商收入是amount-fee，只有在最后成交的时候才会扣费用',
  `status` int(3) unsigned NOT NULL COMMENT '状态状态1已完成;2待接单,3待付款,4待收款,5,申诉中100已取消',
  `credential_urls` varchar(560) DEFAULT NULL COMMENT '支付凭证的图片链接',
  `credential_comment` varchar(400) DEFAULT NULL COMMENT '上传支付凭证的说明',
  `bank_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '银行类型，0：普通银行，1：支付宝，2：微信支付',
  `bank_user` varchar(32) DEFAULT NULL COMMENT '收款的银行账户名',
  `bank_name` varchar(40) DEFAULT NULL COMMENT '收款银行名称',
  `bank_no` varchar(50) DEFAULT NULL COMMENT '收款银行卡号码',
  `receipt_code` varchar(256) DEFAULT '收款码',
  `cancel_type` varchar(8) DEFAULT NULL COMMENT '取消类型，缩写，只有状态为取消才有意义',
  `cancel_comment` varchar(200) DEFAULT NULL COMMENT '取消的时候输入的备注信息',
  `remake` varchar(255) DEFAULT NULL COMMENT '下单时备注信息',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no_UNIQUE` (`order_no`),
  KEY `fk_order_user_id_idx` (`user_id`),
  KEY `fk_order_merchant_id_idx` (`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='由普通用户向兑换商发起的订单，用户买卖基本货币';

#
# Structure for table "t_user_reward_log"
#

CREATE TABLE `t_user_reward_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL COMMENT '用户ID',
  `from` int(11) DEFAULT NULL COMMENT '来源',
  `reason` varchar(10) DEFAULT NULL,
  `coin_name` varchar(8) DEFAULT NULL COMMENT '币名',
  `amount` decimal(32,8) DEFAULT NULL COMMENT '币数',
  `comment` varchar(32) DEFAULT NULL COMMENT '注释',
  `status` int(11) DEFAULT '0' COMMENT '0未发放,1发放',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_userid_from_reason` (`user_id`,`from`,`reason`,`coin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_user_token"
#

CREATE TABLE `t_user_token` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `token` varchar(64) NOT NULL COMMENT 'token',
  `expire_time` datetime NOT NULL COMMENT '过期时间',
  `last_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_userId` (`user_id`),
  KEY `idx_token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Structure for table "t_user_trade_stat"
#

CREATE TABLE `t_user_trade_stat` (
  `id` bigint(16) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `coin_name` varchar(8) NOT NULL DEFAULT '' COMMENT '交易币种名称',
  `settlement_currency` varchar(8) NOT NULL DEFAULT '' COMMENT '结算货币名称',
  `coin_buy_total` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户所有买入单所买入的数字货币总量',
  `settlement_buy_total` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户所有买入单所花费的结算货币总量',
  `coin_sell_total` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户所有卖出单所卖出的数字货币总量',
  `settlement_sell_total` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户所有卖出单所收入的结算货币总量',
  `hold_coin` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户持币量，冗余字段（虚拟的，等于买入总量-卖出总量）（coin_buy_total-coin_sell_total）',
  `settlement_use_total` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '总花费的结算货币的数量（冗余字段，等于settlement_buy_total-settlement_sell_total）',
  `coin_fee` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户买入时收取的所有交易币种手续费总和',
  `settlement_fee` decimal(40,8) NOT NULL DEFAULT '0.00000000' COMMENT '用户卖出是收取的所有结算货币手续费总和',
  `first_trade_log_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '本统计第一个成交的交易日志的id',
  `last_trade_log_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '本统计最后一个成交的交易日志的id',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`,`coin_name`,`settlement_currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='统计每个用户的交易情况';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
