package com.cmd.exchange.common.model;

import com.cmd.exchange.common.enums.MarketStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_market
 *
 * @mbg.generated do_not_delete_during_merge Fri Jun 22 17:50:58 CST 2018
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
public class Market implements Serializable {
    private static final long serialVersionUID = -1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.id
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private Integer id;

    //就是 coinName_settlementCurrency, 方便搜索
    private String name;

    /**
     * Database Column Remarks:
     * 需要买入或卖出的币种，作为货物
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.coin_name
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private String coinName;

    /**
     * Database Column Remarks:
     * 用于结算的货币，一般是平台的基本货币
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.settlement_currency
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private String settlementCurrency;

    /**
     * Database Column Remarks:
     * 市场启用的时间，主要是日期，说明该市场从什么时候开始上市
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.on_market_time
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private Date onMarketTime;

    /**
     * Database Column Remarks:
     * 每天交易开始时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.day_exchange_begin
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private String dayExchangeBegin;

    /**
     * Database Column Remarks:
     * 每天交易结束时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.day_exchange_end
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private String dayExchangeEnd;

    /**
     * Database Column Remarks:
     * 昨天交易金额，收盘价
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.last_day_price
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private BigDecimal lastDayPrice;

    /**
     * Database Column Remarks:
     * 最大涨幅，按照百分比计算，这里是*100后的结果
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.max_increase
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private Integer maxIncrease;

    /**
     * Database Column Remarks:
     * 最大跌幅，按照百分比计算，这里是*100后的结果
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.min_decrease
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private Integer minDecrease;

    /**
     * Database Column Remarks:
     * 每次最小下单的数量
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.min_exchange_num
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private BigDecimal minExchangeNum;

    /**
     * Database Column Remarks:
     * 每次最大下单的数量
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.max_exchange_num
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private BigDecimal maxExchangeNum;

    /**
     * 交易已经产生的币种(获取)费用比例，对于买入：收入的币中少了这个比例的数量，对于卖出：没损失
     */
    private BigDecimal feeCoin;

    /**
     * 交易费用，收取结算货币的比例
     */
    private BigDecimal feeCurrency;

    /**
     * 在该市场扣除的数字货币的费用将会转移到这个用户上面
     */
    private Integer feeCoinUserId;

    /**
     * 在该市场扣除的结算货币的费用将会转移到这个用户上面
     */
    private Integer feeCurrencyUserId;

    /**
     * 最大下单总价，如果是0或者null，那么不控制下单价格
     */
    private BigDecimal maxCurrency;

    /**
     * Database Column Remarks:
     * 是否关闭交易，0表示市场开放，1表示关闭交易
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_market.closed
     *
     * @mbg.generated Fri Jun 22 17:50:58 CST 2018
     */
    private MarketStatus closed;

    private Date createTime;
    private Date lastUpdateTime;
    private String coinUrl;


}