package com.cmd.exchange.common.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_merchant_order
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
public class MerchantOrder implements Serializable {
    private static final long serialVersionUID = -1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 订单号，创建订单的时候自动生成
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.order_no
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     * 订单类型，1：充值，2：提现
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.type
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Boolean type;

    /**
     * Database Column Remarks:
     * 需要买入或卖出的币种，目前固定为平台的基本货币
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.coin_name
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String coinName;

    /**
     * Database Column Remarks:
     * 下单的用户
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.user_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     * 接单的兑换商id，0表示没有人接单
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.super_merchant_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer superMerchantId;

    /**
     * Database Column Remarks:
     * 需要充值或提现的总量
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.amount
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     * 用于结算的货币，一般是CNY或USD
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.settlement_currency
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String settlementCurrency;

    /**
     * Database Column Remarks:
     * 订单创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.add_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     * 接单时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.accept_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer acceptTime;

    /**
     * Database Column Remarks:
     * 上传凭证时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.proof_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer proofTime;

    /**
     * Database Column Remarks:
     * 结束时间，是订单完成或者取消的时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.finish_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer finishTime;

    /**
     * Database Column Remarks:
     * 产生的费用，对于充值（买），最后用户收入是amount-fee,对于提现（卖），最后兑换商收入是amount-fee，只有在最后成交的时候才会扣费用
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.fee
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal fee;

    /**
     * Database Column Remarks:
     * 状态状态1已完成;2待接单,3待付款,4待收款,5,申诉中100已取消
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.status
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer status;

    /**
     * Database Column Remarks:
     * 支付凭证的图片链接
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.credential_urls
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String credentialUrls;

    /**
     * Database Column Remarks:
     * 上传支付凭证的说明
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.credential_comment
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String credentialComment;

    /**
     * Database Column Remarks:
     * 收款的银行账户名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.bank_user
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String bankUser;

    /**
     * Database Column Remarks:
     * 收款银行名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.bank_name
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String bankName;

    /**
     * Database Column Remarks:
     * 收款银行卡号码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.bank_no
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String bankNo;

    /**
     * Database Column Remarks:
     * 取消类型，缩写，只有状态为取消才有意义
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.cancel_type
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String cancelType;

    /**
     * Database Column Remarks:
     * 取消的时候输入的备注信息
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_order.cancel_comment
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String cancelComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.id
     *
     * @return the value of t_merchant_order.id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.id
     *
     * @param id the value for t_merchant_order.id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.order_no
     *
     * @return the value of t_merchant_order.order_no
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.order_no
     *
     * @param orderNo the value for t_merchant_order.order_no
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.type
     *
     * @return the value of t_merchant_order.type
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.type
     *
     * @param type the value for t_merchant_order.type
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.coin_name
     *
     * @return the value of t_merchant_order.coin_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCoinName() {
        return coinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.coin_name
     *
     * @param coinName the value for t_merchant_order.coin_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCoinName(String coinName) {
        this.coinName = coinName == null ? null : coinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.user_id
     *
     * @return the value of t_merchant_order.user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.user_id
     *
     * @param userId the value for t_merchant_order.user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.super_merchant_id
     *
     * @return the value of t_merchant_order.super_merchant_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getSuperMerchantId() {
        return superMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.super_merchant_id
     *
     * @param superMerchantId the value for t_merchant_order.super_merchant_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setSuperMerchantId(Integer superMerchantId) {
        this.superMerchantId = superMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.amount
     *
     * @return the value of t_merchant_order.amount
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.amount
     *
     * @param amount the value for t_merchant_order.amount
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.settlement_currency
     *
     * @return the value of t_merchant_order.settlement_currency
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getSettlementCurrency() {
        return settlementCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.settlement_currency
     *
     * @param settlementCurrency the value for t_merchant_order.settlement_currency
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setSettlementCurrency(String settlementCurrency) {
        this.settlementCurrency = settlementCurrency == null ? null : settlementCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.add_time
     *
     * @return the value of t_merchant_order.add_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.add_time
     *
     * @param addTime the value for t_merchant_order.add_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.accept_time
     *
     * @return the value of t_merchant_order.accept_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.accept_time
     *
     * @param acceptTime the value for t_merchant_order.accept_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAcceptTime(Integer acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.proof_time
     *
     * @return the value of t_merchant_order.proof_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getProofTime() {
        return proofTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.proof_time
     *
     * @param proofTime the value for t_merchant_order.proof_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setProofTime(Integer proofTime) {
        this.proofTime = proofTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.finish_time
     *
     * @return the value of t_merchant_order.finish_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.finish_time
     *
     * @param finishTime the value for t_merchant_order.finish_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setFinishTime(Integer finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.fee
     *
     * @return the value of t_merchant_order.fee
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.fee
     *
     * @param fee the value for t_merchant_order.fee
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.status
     *
     * @return the value of t_merchant_order.status
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.status
     *
     * @param status the value for t_merchant_order.status
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.credential_urls
     *
     * @return the value of t_merchant_order.credential_urls
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCredentialUrls() {
        return credentialUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.credential_urls
     *
     * @param credentialUrls the value for t_merchant_order.credential_urls
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCredentialUrls(String credentialUrls) {
        this.credentialUrls = credentialUrls == null ? null : credentialUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.credential_comment
     *
     * @return the value of t_merchant_order.credential_comment
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCredentialComment() {
        return credentialComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.credential_comment
     *
     * @param credentialComment the value for t_merchant_order.credential_comment
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCredentialComment(String credentialComment) {
        this.credentialComment = credentialComment == null ? null : credentialComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.bank_user
     *
     * @return the value of t_merchant_order.bank_user
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.bank_user
     *
     * @param bankUser the value for t_merchant_order.bank_user
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.bank_name
     *
     * @return the value of t_merchant_order.bank_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.bank_name
     *
     * @param bankName the value for t_merchant_order.bank_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.bank_no
     *
     * @return the value of t_merchant_order.bank_no
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.bank_no
     *
     * @param bankNo the value for t_merchant_order.bank_no
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.cancel_type
     *
     * @return the value of t_merchant_order.cancel_type
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCancelType() {
        return cancelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.cancel_type
     *
     * @param cancelType the value for t_merchant_order.cancel_type
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCancelType(String cancelType) {
        this.cancelType = cancelType == null ? null : cancelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_order.cancel_comment
     *
     * @return the value of t_merchant_order.cancel_comment
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCancelComment() {
        return cancelComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_order.cancel_comment
     *
     * @param cancelComment the value for t_merchant_order.cancel_comment
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCancelComment(String cancelComment) {
        this.cancelComment = cancelComment == null ? null : cancelComment.trim();
    }
}