package com.cmd.exchange.common.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_bill
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
public class MerchantBill implements Serializable {
    private static final long serialVersionUID = -266183044697252605L;

    // 定义账单子类型
    public static final int SUB_TYPE_AVAILABLE = 0;    // 可用基金变化
    public static final int SUB_TYPE_FREEZE = 1;    //  冻结基金变化

    // 定义原因
    public static final String C2B_USER_SELL_COIN = "USellC";       // 普通用户卖数字货币给兑换商，兑换商买入普通用户的数字货币
    public static final String C2B_USER_BUY_COIN = "UBuyC";        // 普通用户买兑换商的数字货币，兑换商卖出数字货币
    public static final String B2B_MER_SELL_COIN = "MSellC";       // 普通兑换商卖数字货币给超级兑换商，超级兑换商买入普通兑换商的数字货币
    public static final String B2B_MER_BUY_COIN = "MBuyC";        // 普通兑换商买超级兑换商的数字货币，超级兑换商卖出数字货币
    public static final String C2B_CANCEL = "Cancel";       //  兑换商取消订单
    public static final String C2B_MGR_CANCEL = "MgrCc";        //  管理员取消订单


    private Integer id;

    private Integer merchantId;

    /**
     * Database Column Remarks:
     * 变化的币种名称，缩写，编译查看
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.coin_name
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String coinName;

    /**
     * Database Column Remarks:
     * 子类型，0：该币种的正常的余额变化，1：表示是该币种冻结金变化
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.sub_type
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Boolean subType;

    /**
     * Database Column Remarks:
     * 资金变化原因，比如received:收到尾部转入，send:转出等
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.reason
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String reason;

    /**
     * Database Column Remarks:
     * 变化大小，正数表示增加金额，负数表示减少金额
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.change_amount
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal changeAmount;


    /**
     * Database Column Remarks:
     * 备注信息，记录一些额外信息，比如变化的订单号等
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.comment
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String comment;


    private Date lastTime;

}