package com.cmd.exchange.common.model;

import com.cmd.exchange.common.enums.BankType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_merchant
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel("兑换商基本信息")
public class Merchant implements Serializable {
    private static final long serialVersionUID = -145346456544544L;

    public static final int TYPE_NORMAL = 1;   // 普通兑换商
    public static final int TYPE_SUPER = 2;   // 超级兑换商

    public static final int WORK_STATUS_WORK = 1;   // 正常工作
    public static final int WORK_STATUS_STOP = 0;   // 不工作不接单

    public static final int STATUS_NORMAL = 0;     // 正常
    public static final int STATUS_DISABLE = 1;     // 已经禁用
    public static final int STATUS_APPLY = 2;     // 申请中
    public static final int STATUS_REJECT = 3;     // 已经拒绝


    private Integer id;

    /**
     * 所属的用户id
     */
    private Integer userId;

    @ApiModelProperty(value = "兑换商名称")
    private String name;

    @ApiModelProperty(value = "兑换商电话")
    private String phone;

    @ApiModelProperty(value = "兑换商邮箱地址")
    private String email;

    @ApiModelProperty(value = "兑换商类型，1：普通兑换商，2：超级兑换商")
    private Integer type;

    @ApiModelProperty(value = "状态，0：正常，1：已经禁用，2：申请中，3：已经拒绝")
    private Integer status;

    @ApiModelProperty(value = "工作状态（表示兑换商自己是否接单），1：正常工作，0：不工作不接单")
    private Integer workingStatus;


    @ApiModelProperty(value = "银行类型，BANK：银行，ALIPAY：支付宝，WEIXIN：微信")
    private BankType bankType;

    @ApiModelProperty(value = "兑换商银行账户名")
    private String bankUser;

    @ApiModelProperty(value = "兑换商银行名称")
    private String bankName;

    @ApiModelProperty(value = "兑换商银行卡号码")
    private String bankNo;

    /**
     * 创建时间
     */
    private Integer addTime;

    @ApiModelProperty("审核不通过的原因")
    private String reason;

}