package com.cmd.exchange.common.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_received_coin
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
public class ReceivedCoin implements Serializable {
    private static final long serialVersionUID = -1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 收到钱的用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.user_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     * 收到转账的地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.address
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String address;

    /**
     * Database Column Remarks:
     * 币种名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.coin_name
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String coinName;

    /**
     * Database Column Remarks:
     * 转账的交易id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.txid
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String txid;

    /**
     * Database Column Remarks:
     * 收到外部的金额大小
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.amount
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     * 转入收取的费用，最后到账的金额是amount-fee
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.fee
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal fee;

    /**
     * Database Column Remarks:
     * 交易时间，是交易产生的时间，一般是区块链区块的时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.tx_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Date txTime;

    /**
     * Database Column Remarks:
     * 收到的时间，一般是记录创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.received_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Date receivedTime;

    /**
     * Database Column Remarks:
     * 状态，1：已经收到
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_received_coin.status
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.id
     *
     * @return the value of t_received_coin.id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.id
     *
     * @param id the value for t_received_coin.id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.user_id
     *
     * @return the value of t_received_coin.user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.user_id
     *
     * @param userId the value for t_received_coin.user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.address
     *
     * @return the value of t_received_coin.address
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.address
     *
     * @param address the value for t_received_coin.address
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.coin_name
     *
     * @return the value of t_received_coin.coin_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCoinName() {
        return coinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.coin_name
     *
     * @param coinName the value for t_received_coin.coin_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCoinName(String coinName) {
        this.coinName = coinName == null ? null : coinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.txid
     *
     * @return the value of t_received_coin.txid
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.txid
     *
     * @param txid the value for t_received_coin.txid
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setTxid(String txid) {
        this.txid = txid == null ? null : txid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.amount
     *
     * @return the value of t_received_coin.amount
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.amount
     *
     * @param amount the value for t_received_coin.amount
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.fee
     *
     * @return the value of t_received_coin.fee
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.fee
     *
     * @param fee the value for t_received_coin.fee
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    public Date getTxTime() {
        return txTime;
    }

    public void setTxTime(Date txTime) {
        this.txTime = txTime;
    }

    public Date getReceivedTime() {
        return receivedTime;
    }

    public void setReceivedTime(Date receivedTime) {
        this.receivedTime = receivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_received_coin.status
     *
     * @return the value of t_received_coin.status
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_received_coin.status
     *
     * @param status the value for t_received_coin.status
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}