package com.cmd.exchange.common.model;

import com.cmd.exchange.common.enums.SendCoinStatus;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_send_coin
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
public class SendCoin implements Serializable {
    private static final long serialVersionUID = -1402494593;

    private Integer id;
    //转出钱的用户id
    private Integer userId;
    //用户名
    private String userName;
    //收款的用户id，只有在内部转账的时候才会有
    private Integer receivedUserId;
    //收款的地址
    private String address;
    //币种名称
    private String coinName;
    //转账的交易id
    private String txid;
    //转账外部的金额大小
    private BigDecimal amount;
    //转账费用
    private BigDecimal fee;
    //发送的时间，一般是记录创建时间
    private Date sendTime;
    //状态，1：已经成功发出
    private SendCoinStatus status;

    private Date lastTime;
    @ApiModelProperty("用户类型")
    private String groupType;

    @ApiModelProperty("用户类型名")
    private String groupName;

    @ApiModelProperty("二次审核状态,此状态和第一次状态关联：（0,1）表示第一审核通过，第一次审核状态 为1.表示审核通过 ，第一次审核状态为2为拒绝。")
    private String secondStatus;

    @ApiModelProperty("真实姓名")
    private String realName;
}


