package com.cmd.exchange.common.model;

import lombok.Data;

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_trade_log
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Data
public class TradeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     * 需要买入或卖出的币种，作为货物
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.coin_name
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String coinName;

    /**
     * Database Column Remarks:
     * 用于结算的货币，一般是平台的基本货币
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.settlement_currency
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String settlementCurrency;

    /**
     * Database Column Remarks:
     * 购买或卖出币种的单价，就是买入或卖出1个coin_name所对应的结算货币的个数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.price
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     * 本次交易卖出或卖出币种/货物的数量
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.amount
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     * 买房用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.buy_user_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer buyUserId;

    /**
     * Database Column Remarks:
     * 卖方用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.sell_user_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer sellUserId;

    /**
     * Database Column Remarks:
     * 交易发生的时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.add_time
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     * 本次交易产生买入费用，因为买入收入的是币（货物），所以这里是币的数量，买入方最后收入是amount-fee_buy
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.buy_fee_coin
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal buyFeeCoin;

    /**
     * Database Column Remarks:
     * 本次交易产生卖出费用，因为卖出收入的是结算货币，所以这里是结算货币的数量，卖入方最后收入是price*amount-fee_sell
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.sell_fee_currency
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal sellFeeCurrency;

    /**
     * Database Column Remarks:
     * 买方的t_trade表中的交易请求id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.buy_trade_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer buyTradeId;

    /**
     * Database Column Remarks:
     * 卖方的t_trade表中的交易请求id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_log.sell_trade_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer sellTradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.id
     *
     * @return the value of t_trade_log.id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.id
     *
     * @param id the value for t_trade_log.id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.coin_name
     *
     * @return the value of t_trade_log.coin_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getCoinName() {
        return coinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.coin_name
     *
     * @param coinName the value for t_trade_log.coin_name
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setCoinName(String coinName) {
        this.coinName = coinName == null ? null : coinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.settlement_currency
     *
     * @return the value of t_trade_log.settlement_currency
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public String getSettlementCurrency() {
        return settlementCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.settlement_currency
     *
     * @param settlementCurrency the value for t_trade_log.settlement_currency
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setSettlementCurrency(String settlementCurrency) {
        this.settlementCurrency = settlementCurrency == null ? null : settlementCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.price
     *
     * @return the value of t_trade_log.price
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.price
     *
     * @param price the value for t_trade_log.price
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.amount
     *
     * @return the value of t_trade_log.amount
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.amount
     *
     * @param amount the value for t_trade_log.amount
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.buy_user_id
     *
     * @return the value of t_trade_log.buy_user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getBuyUserId() {
        return buyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.buy_user_id
     *
     * @param buyUserId the value for t_trade_log.buy_user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setBuyUserId(Integer buyUserId) {
        this.buyUserId = buyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.sell_user_id
     *
     * @return the value of t_trade_log.sell_user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getSellUserId() {
        return sellUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.sell_user_id
     *
     * @param sellUserId the value for t_trade_log.sell_user_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setSellUserId(Integer sellUserId) {
        this.sellUserId = sellUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.add_time
     *
     * @return the value of t_trade_log.add_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.add_time
     *
     * @param addTime the value for t_trade_log.add_time
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.buy_fee_coin
     *
     * @return the value of t_trade_log.buy_fee_coin
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getBuyFeeCoin() {
        return buyFeeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.buy_fee_coin
     *
     * @param buyFeeCoin the value for t_trade_log.buy_fee_coin
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setBuyFeeCoin(BigDecimal buyFeeCoin) {
        this.buyFeeCoin = buyFeeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.sell_feel_currency
     *
     * @return the value of t_trade_log.sell_feel_currency
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public BigDecimal getSellFeeCurrency() {
        return sellFeeCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.sell_feel_currency
     *
     * @param sellFeeCurrency the value for t_trade_log.sell_feel_currency
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setSellFeeCurrency(BigDecimal sellFeeCurrency) {
        this.sellFeeCurrency = sellFeeCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.buy_trade_id
     *
     * @return the value of t_trade_log.buy_trade_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getBuyTradeId() {
        return buyTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.buy_trade_id
     *
     * @param buyTradeId the value for t_trade_log.buy_trade_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setBuyTradeId(Integer buyTradeId) {
        this.buyTradeId = buyTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_log.sell_trade_id
     *
     * @return the value of t_trade_log.sell_trade_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public Integer getSellTradeId() {
        return sellTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_log.sell_trade_id
     *
     * @param sellTradeId the value for t_trade_log.sell_trade_id
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    public void setSellTradeId(Integer sellTradeId) {
        this.sellTradeId = sellTradeId;
    }
}