package com.cmd.exchange.common.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Getter
@Setter
@NoArgsConstructor
@Accessors(chain = true)
@JsonIgnoreProperties(value = {"payPassword", "password", "salt", "paySalt", "token"})
public class User implements Serializable {

    private static final long serialVersionUID = -1661830493897252605L;

    public static final int USER_TYPE_USER = 0;   // 用户类型，普通用户
    public static final int USER_TYPE_SUPER_NODE = 1;   // 用户类型，超级节点

    private Integer id;

    //用户登录名称，全表唯一
    private String userName;
    //国家代码（86）
    private String areaCode;
    //用户绑定的手机号码
    private String mobile;
    private String password;
    private String salt;
    private String payPassword;
    private String paySalt;
    //邀请码
    private String inviteCode;
    private Integer referrer;//推荐人id
    //用户真实姓名
    private String realName;
    //实名验证的证件类型，0是默认表示没有认真，1表示中国居民身份证，2是国际护照
    private Integer idCardType;
    //实名验证的证件号码
    private String idCard;
    //实名验证状态，0，未实名验证，1，等待身份证验证，2：身份证号码验证通过
    private int realNameStatus;
    //实名验证的图片1
    private String idCardImg1;
    //实名验证的图片2
    private String idCardImg2;
    //实名验证的图片3
    private String idCardImg3;
    //图片实名验证的状态，0：没有实名验证通过，1： 已经实名验证通过，2：已经提交实名验证，待验证，3：实名验证失败，退回用户重新提交
    private Integer idCardStatus;
    //图片实名验证的注册时间
    private Date idCardTime;
    //当前实名验证的一些额外备注信息，比如验证失败原因
    private String idCardInfo;
    //用户登录次数
    private Integer loginTimes;
    //注册时的ip
    private String registerIp;
    //最近一次登录的用户ip
    private String lastLoginIp;
    //注册时间
    private Date registerTime;
    //最后一次登录时间
    private Date lastLoginTime;
    //用户状态，0：正常，1：被禁用
    private Integer status;
    //邮箱
    private String email;
    //最后一次用户修改资料的时间，登录不修改这个时间
    private Date updateTime;

    //存储在内存中的token
    private String token;
    //玩家分组 0 ：无分组 A,B,C,D
    private String groupType;
    // 用户类型0，正常用户，1：超级节点
    private Integer userType;
    //是否有发布OTC权限，1有，其他没有
    private Integer isPublishOtc;
    //用户头像
    private String image;

}