package com.cmd.exchange.common.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_coin
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Getter
@Setter
@Data
@NoArgsConstructor
@Accessors(chain = true)
public class UserCoin implements Serializable {
    private static final long serialVersionUID = -1661830493897252605L;

    public static final Integer VIP_TYPE_USER = 0;   // 非VIP
    public static final Integer VIP_TYPE_VIP = 1;   // VIP用户

    private Integer id;
    private Integer userId;
    @ApiModelProperty(value = "币种名称")
    private String coinName;
    private String bindAddress;
    @ApiModelProperty(value = "可用余额")
    private BigDecimal availableBalance;
    @ApiModelProperty(value = "冻结余额")
    private BigDecimal freezeBalance;
    @ApiModelProperty(value = "转入冻结，另外一种冻结金")
    private BigDecimal receiveFreezeBalance;
    @ApiModelProperty(value = "用户该币种VIP类型，0，不是vip，1：vip")
    private Integer vipType;

    //用户币种状态，0：正常，1：冻结使用
    private Integer status;


}