package com.cmd.exchange.common.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_bill
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 21 10:03:28 CST 2018
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
public class UserBill implements Serializable {
    private static final long serialVersionUID = -1661830493897252605L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigInteger id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.user_id
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     * 变化的币种名称，缩写，编译查看
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.coin_name
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String coinName;

    /**
     * Database Column Remarks:
     * 子类型，0：该币种的正常的余额变化，1：表示是该币种冻结金变化
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.sub_type
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private Boolean subType;

    /**
     * Database Column Remarks:
     * 资金变化原因，比如received:收到尾部转入，send:转出等
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.reason
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String reason;

    /**
     * Database Column Remarks:
     * 变化大小，正数表示增加金额，负数表示减少金额
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.change_amount
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private BigDecimal changeAmount;


    /**
     * Database Column Remarks:
     * 备注信息，记录一些额外信息，比如变化的订单号等
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bill.comment
     *
     * @mbg.generated Thu Jun 21 10:03:28 CST 2018
     */
    private String comment;


    private Date lastTime;

}